import React,{useState,useRef,useEffect} from 'react'
import logo from '../../public/images/logo_v7.png'
import smallLogo from '../../public/images/nficon2016.ico'
import avatar from '../../public/images/avatar.png'

import Image from 'next/image'
import Link from 'next/link';
import Head from 'next/head'
import {useRouter} from 'next/router'

import { GoSearch } from "react-icons/go";
import { AiOutlineCaretDown } from "react-icons/ai";
import { AnimatePresence,motion } from 'framer-motion';

import { signOut } from 'firebase/auth';
import { auth } from '../../firebase';

const Header = ({transparent}) => {
  const router = useRouter();
  const [scrollPosition, setScrollPosition] = useState(0);

  const color = scrollPosition>150?"bg-black":"bg-gradient-to-b from-black to-transparent";

  const [searchIsOpen,setSearchIsOpen] = useState(false);
  const [dropDownIsOpen,setDropDownIsOpen] = useState(false);
  const searchInputRef = useRef();
  const searchButton = useRef();

  useEffect(() => {
    const handleScroll = () => {
      const currentScrollY = window.scrollY;
      setScrollPosition(currentScrollY);
    };
    window.addEventListener("scroll", handleScroll, { passive: true });
    return () => window.removeEventListener("scroll", handleScroll);
  }, [scrollPosition]);

  const searchClickHandler = () =>{
    if(searchIsOpen){
      const value = searchInputRef.current.value.trim();
      if(value!=""){
        router.push(`/search/${value}`);
      }else{
        setSearchIsOpen(false);
      }
    }else{
      setSearchIsOpen(true);
    }
  }

  const handleInputEnter = (e) =>{
    if (e.key === 'Enter') {
      searchButton.current.click();
    }
  }

  return (
    <>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/nficon2016.ico" />
      </Head>
      <div>
        <div className={"fixed z-50 w-full text-white flex flex-row items-center justify-between py-5 px-4 sm:px-8"+" "+color}>
          <div className='flex flex-row gap-6'>
            <div className="">
              <Link href="/home">
                <a>
                  <div className="w-24 h-full hidden sm:flex items-center">
                    <Image src={logo} alt="logo"/>
                  </div>
                  <div className="w-10 h-full flex items-center sm:hidden mr-2">
                    <Image src={smallLogo} alt="logo"/>
                  </div>
                </a>
              </Link>
              
            </div>
            <ul className="flex-row gap-4 hidden lg:flex">
              <li><Link href="/home"><a>Home</a></Link></li>
              <li><a href="#">Movies</a></li>
              <li><a href="#">TV Shows</a></li>
              <li><a href="#">My List</a></li>
            </ul> 
          </div>

          <div>
            <div id="search-bar">

            </div>
            <div className="flex flex-row items-center gap-1 sm:gap-2">
                <div className="mr-3 flex flex-row items-center gap-3">
                  <div className='w-36 h-8 sm:w-auto sm:h-auto'>
                    <AnimatePresence>
                    {searchIsOpen 
                    && 
                    <motion.input 
                      initial={{opacity:0}}
                      animate={{opacity:1}}
                      exit={{opacity:0}}
                      ref={searchInputRef}
                      type="text" 
                      placeholder="Search movies, TV Shows" 
                      className='bg-transparent border-[1px] border-white rounded-lg outline-none px-1 sm:px-3 py-1 placeholder:text-white placeholder:text-opacity-80 text-sm w-full'
                      onKeyDown={(handleInputEnter)}
                      />
                    }
                    </AnimatePresence>
                  </div>

                  <button onClick={searchClickHandler} ref={searchButton}><GoSearch className="text-xl"/></button>
                </div>
                <div className="w-8 sm:w-10 rounded overflow-hidden flex flex-row items-center">
                  <Image src={avatar} alt="avatar" className='rounded'/>
                </div>
                <div className="p-1 rounded-full border-2 border-transparent hover:border-white relative cursor-pointer" onClick={()=>dropDownIsOpen?setDropDownIsOpen(false):setDropDownIsOpen(true)}>
                  <AiOutlineCaretDown className="text-sm"/>
                  <AnimatePresence>
                  {dropDownIsOpen 
                    && 
                  <motion.div 
                    initial={{ height: 0,opacity:0}}
                    animate={{ height: 'auto',opacity:1}}
                    className='absolute bg-neutral-800 right-0 top-[190%] rounded'>
                    <div className="py-3 px-5">
                      <ul className="flex flex-col gap-3 lg:hidden w-auto mb-3 text-center">
                        <li><Link href="/home"><a>Home</a></Link></li>
                        <li><a href="#">Movies</a></li>
                        <li><a href="#">TV Shows</a></li>
                        <li><a href="#">My List</a></li>
                      </ul> 
                      <button className="bg-redBtn py-1 px-4 rounded mb-2" onClick={()=>router.push("/account")}>Account</button>
                      <button className="bg-redBtn py-1 px-4 rounded" onClick={()=>signOut(auth)}>Sign out</button> 
                    </div>
                  </motion.div>
                  }
                  </AnimatePresence>
                </div>
            </div>
          </div>
        </div>
      </div>

    </>
  )
}

export default Header