import React, { useEffect } from 'react'

import Head from 'next/head'
import LoginLayout from '../../components/Layouts/LoginLayout/LoginLayout'
import SignIn from '../../components/SignIn/SignIn'
import { useAuthState } from 'react-firebase-hooks/auth';
import {auth} from '../../firebase';
import {useRouter} from 'next/router'

const Login = () => {
  const [user, loading, error] = useAuthState(auth);
  const router = useRouter();

  useEffect(()=>{
    if(user){
      user.emailVerified && router.push("/home");
    }
  },[user,router])

  return (
    <>
      <Head>
          <title>Netflix</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/images/nficon2016.ico" />
      </Head>

      <LoginLayout>
        <SignIn/>
      </LoginLayout>
    </>
  )
}

export default Login